node output-grpc/beaconGetBaseEpoch.js >> output-grpc/beaconGetBaseEpoch.js
node output-grpc/consensusGetChainContext.js >> output-grpc/consensusGetChainContext.js
node output-grpc/consensusGetGenesisDocument.js >> output-grpc/consensusGetGenesisDocument.js
node output-grpc/consensusGetNextBlockState.js >> output-grpc/consensusGetNextBlockState.js
node output-grpc/consensusGetStatus.js >> output-grpc/consensusGetStatus.js
node output-grpc/consensusGetUnconfirmedTransactions.js >> output-grpc/consensusGetUnconfirmedTransactions.js
node output-grpc/nodeControllerGetStatus.js >> output-grpc/nodeControllerGetStatus.js
node output-grpc/stakingTokenSymbol.js >> output-grpc/stakingTokenSymbol.js
node output-grpc/stakingTokenValueExponent.js >> output-grpc/stakingTokenValueExponent.js
node output-grpc/beaconConsensusParameters.js >> output-grpc/beaconConsensusParameters.js
node output-grpc/beaconGetBeacon.js >> output-grpc/beaconGetBeacon.js
node output-grpc/beaconGetEpoch.js >> output-grpc/beaconGetEpoch.js
node output-grpc/beaconGetFutureEpoch.js >> output-grpc/beaconGetFutureEpoch.js
node output-grpc/consensusGetBlock.js >> output-grpc/consensusGetBlock.js
node output-grpc/consensusGetParameters.js >> output-grpc/consensusGetParameters.js
node output-grpc/consensusGetTransactions.js >> output-grpc/consensusGetTransactions.js
node output-grpc/consensusGetTransactionsWithResults.js >> output-grpc/consensusGetTransactionsWithResults.js
node output-grpc/governanceActiveProposals.js >> output-grpc/governanceActiveProposals.js
node output-grpc/governanceConsensusParameters.js >> output-grpc/governanceConsensusParameters.js
node output-grpc/governanceGetEvents.js >> output-grpc/governanceGetEvents.js
node output-grpc/governancePendingUpgrades.js >> output-grpc/governancePendingUpgrades.js
node output-grpc/governanceProposals.js >> output-grpc/governanceProposals.js
node output-grpc/registryConsensusParameters.js >> output-grpc/registryConsensusParameters.js
node output-grpc/registryGetEntities.js >> output-grpc/registryGetEntities.js
node output-grpc/registryGetEvents.js >> output-grpc/registryGetEvents.js
node output-grpc/registryGetNodes.js >> output-grpc/registryGetNodes.js
node output-grpc/rootHashConsensusParameters.js >> output-grpc/rootHashConsensusParameters.js
node output-grpc/rootHashGetEvents.js >> output-grpc/rootHashGetEvents.js
node output-grpc/schedulerConsensusParameters.js >> output-grpc/schedulerConsensusParameters.js
node output-grpc/schedulerGetValidators.js >> output-grpc/schedulerGetValidators.js
node output-grpc/stakingAddresses.js >> output-grpc/stakingAddresses.js
node output-grpc/stakingCommissionScheduleAddresses.js >> output-grpc/stakingCommissionScheduleAddresses.js
node output-grpc/stakingCommonPool.js >> output-grpc/stakingCommonPool.js
node output-grpc/stakingConsensusParameters.js >> output-grpc/stakingConsensusParameters.js
node output-grpc/stakingGetEvents.js >> output-grpc/stakingGetEvents.js
node output-grpc/stakingGovernanceDeposits.js >> output-grpc/stakingGovernanceDeposits.js
node output-grpc/stakingLastBlockFees.js >> output-grpc/stakingLastBlockFees.js
node output-grpc/stakingTotalSupply.js >> output-grpc/stakingTotalSupply.js
node output-grpc/beaconGetEpochBlock.js >> output-grpc/beaconGetEpochBlock.js
node output-grpc/runtimeClientGetGenesisBlock.js >> output-grpc/runtimeClientGetGenesisBlock.js
node output-grpc/runtimeClientGetLastRetainedBlock.js >> output-grpc/runtimeClientGetLastRetainedBlock.js
node output-grpc/governanceProposal.js >> output-grpc/governanceProposal.js
node output-grpc/governanceVotes.js >> output-grpc/governanceVotes.js
node output-grpc/registryGetEntity.js >> output-grpc/registryGetEntity.js
node output-grpc/registryGetNode.js >> output-grpc/registryGetNode.js
node output-grpc/registryGetNodeStatus.js >> output-grpc/registryGetNodeStatus.js
node output-grpc/registryGetNodeByConsensusAddress.js >> output-grpc/registryGetNodeByConsensusAddress.js
node output-grpc/registryGetRuntimes.js >> output-grpc/registryGetRuntimes.js
node output-grpc/rootHashGetGenesisBlock.js >> output-grpc/rootHashGetGenesisBlock.js
node output-grpc/rootHashGetLastRoundResults.js >> output-grpc/rootHashGetLastRoundResults.js
node output-grpc/rootHashGetLatestBlock.js >> output-grpc/rootHashGetLatestBlock.js
node output-grpc/rootHashGetRuntimeState.js >> output-grpc/rootHashGetRuntimeState.js
node output-grpc/runtimeClientGetBlock.js >> output-grpc/runtimeClientGetBlock.js
node output-grpc/runtimeClientGetEvents.js >> output-grpc/runtimeClientGetEvents.js
node output-grpc/runtimeClientGetTransactions.js >> output-grpc/runtimeClientGetTransactions.js
node output-grpc/runtimeClientGetTransactionsWithResults.js >> output-grpc/runtimeClientGetTransactionsWithResults.js
node output-grpc/schedulerGetCommittees.js >> output-grpc/schedulerGetCommittees.js
node output-grpc/stakingAllowance.js >> output-grpc/stakingAllowance.js
node output-grpc/stakingAccount.js >> output-grpc/stakingAccount.js
node output-grpc/stakingDebondingDelegationInfosFor.js >> output-grpc/stakingDebondingDelegationInfosFor.js
node output-grpc/stakingDebondingDelegationsFor.js >> output-grpc/stakingDebondingDelegationsFor.js
node output-grpc/stakingDebondingDelegationsTo.js >> output-grpc/stakingDebondingDelegationsTo.js
node output-grpc/stakingDelegationInfosFor.js >> output-grpc/stakingDelegationInfosFor.js
node output-grpc/stakingDelegationsFor.js >> output-grpc/stakingDelegationsFor.js
node output-grpc/stakingDelegationsTo.js >> output-grpc/stakingDelegationsTo.js
